sonar.projectKey=RedeArmy_Product-Catalog-Platform
sonar.organization=redearmy

# Project metadata
sonar.projectName= Product Catalog Platform
sonar.projectVersion=1.0

# Source directories
sonar.sources=backend/src,frontend/src

# Language-specific settings
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.cs.vstest.reportsPaths=**/TestResults/*.trx

# Exclusions — don't analyze generated or third-party files
sonar.exclusions=\
  **/bin/**,\
  **/obj/**,\
  **/Migrations/**,\
  **/node_modules/**,\
  **/dist/**,\
  **/*.Designer.cs,\
  **/wwwroot/**

# Coverage exclusions
sonar.coverage.exclusions=\
  **/Program.cs,\
  **/Migrations/**,\
  **/*Dto.cs,\
  **/*Configuration.cs